name: Auto Tweet Generate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.8.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - uses: browser-actions/setup-chromium@latest

      - name: Run download.py
        run: |
          python download.py
      - name: Commit and Push
        run: |
          git config user.name "Murayu0225"
          git config user.email "murayu@assistant-app.com"
          git add .
          git commit -m "Downloaded!" || echo "No changes to commit"
          git pull  origin main
          git push origin main
